### PR TITLE
Added ability to warp while driving in a vehicle

### PR DESCRIPTION
**Pull request by bbassie**
This adds the ability to stay in your vehicle while warping.

Wanted to do this for ease of use with the Spidertron but it is not able to be teleported yet, I've submitted a bug report:
[bug report](https://forums.factorio.com/viewtopic.php?f=7&t=88128)

### CODE REVIEW

**Comment by bbassie** [comment]
Spider feature comming soon: (reply from: Rseding91)
It was marked as not teleportable shortly before the release due to complications with how it worked; it didn't when teleported. So, it's intentional.

However; two days ago I implemented teleporting for them so it will be in some future release.

**Comment by Cooldude2606** [comment]
Has this been made possible yet?

**Comment by bbassie** [comment]
It should be working, if I'm not mistaking it worked last time I tried to do it after the update where they added it.

**Review by Cooldude2606 — APPROVED** [review]
All your changes are good and work correctly. The force pushes were used to remove the merges I preformed before you made your changes. These merges from the release branch only created merge confilcts and should not have been done.

**Pull request merged**
