### PR TITLE
fix: set roles after jailing

### PR DESCRIPTION
**Pull request by oof2win2**

### CODE REVIEW

**Review by Cooldude2606 — CHANGES_REQUESTED** [review]
The logic is almost there; however, I have since discovered aditional edge cases which will not be covered. 
Because of this I suggest moving the logic into `role:add_player` and `role:remove_player`.

You also need to correct the `= 1` and `= -1` to be `+=` and `-=` (lua equivalent) and use `< 0` and `> 0` rather than `== -1` and `== 1`.

**Comment by Cooldude2606** [comment]
@oof2win2 I have implimented the changes I requested in order to get this merged for the upcoming release.
Could you please validate that the bug you reported is now fixed.

**Comment by oof2win2** [comment]
Sorry I didn't get back to this. Currently can't, I'd be able to get back to you on the 25th or 26th. It looks fine by me though if that's enough to merge it

**Comment by oof2win2** [comment]
Looks good to me 👍

**Review by Cooldude2606 — APPROVED** [review]
Self sign-off of own changes after validation from OP.

**Comment by Cooldude2606** [comment]
Bypassing review requirement: New changes are from rebase and so do not include any new code.

**Pull request merged**
