### PR TITLE
Fix auth in GUI not working.

### PR DESCRIPTION
**Pull request by oof2win2**

### CODE REVIEW

**Comment by Cooldude2606** [comment]
Updating the top flow would need to be done inside the event emit as there are 2 other places where this would be needed.
I don't want Roles or Gui to depend on each other, so although this would be very small having its own file would be preferable.
Best solution might be to use `_C.opt_require` inside `gui/_require.lua` to check if the roles module exists then connect to it.

**Comment by oof2win2** [comment]
I believe that a494391  should fix that

**Review by Cooldude2606 — APPROVED** [review]
All looks good to me.

**Comment by Cooldude2606** [comment]
I will be treating this like a patch, so I am changing the base branch to merge into a patch.

**Pull request merged**
